"""
pm — Agent Smith's project-manager routine. "How's the project going?"

Reads tools/project_manager's tracker and phrases a status, the same
value-free way doctor.py does: the `answer` string is built entirely from
counts computed off the stored JSON (tracker.project_report), never
generated by a model and never inventing progress that wasn't logged. If no
project is named in the utterance, reports whichever project was most
recently touched (or the only one, or all of them if none has a log yet).

Slice shape (consumed by the /command render + the PWA, same family as
doctor's):
  {"kind":"pm", "answer":.., "projects":[{...tracker.project_report...}]}
"""

import re
from typing import Any, Dict, List, Optional

from tools.project_manager import tracker


def _match_project(text: str, projects: List[Dict[str, Any]]) -> Optional[str]:
    """If the utterance names a project (by id or a word from its name),
    return its id. Otherwise None — caller falls back to most-recent."""
    low = text.lower()
    for p in projects:
        if p["id"].lower() in low:
            return p["id"]
        name_words = [w for w in re.findall(r"[a-z0-9]+", p["name"].lower()) if len(w) > 3]
        if name_words and all(w in low for w in name_words):
            return p["id"]
        if any(w in low for w in name_words):
            return p["id"]
    return None


async def answer_pm(text: str = "") -> Dict[str, Any]:
    projects = tracker.list_projects()
    if not projects:
        return {"kind": "pm", "answer": "No projects tracked yet.", "projects": []}

    target_id = _match_project(text, projects) if text else None
    if target_id:
        reports = [tracker.project_report(target_id)]
        answer = reports[0]["summary"]
    else:
        recent_id = tracker.most_recent_project_id()
        if recent_id:
            reports = [tracker.project_report(recent_id)]
            answer = reports[0]["summary"]
        else:
            reports = [tracker.project_report(p["id"]) for p in projects]
            answer = " ".join(r["summary"] for r in reports)

    return {"kind": "pm", "answer": answer, "projects": reports}
